In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.ticker import AutoMinorLocator, MaxNLocator

Font chữ và legend cỡ 16pt.

Hình xuất ra rất nét với dpi = 1000.

Trục và ticks rõ ràng, ticks hướng vào trong, major tick dài hơn minor tick.

Trục dày 1.5pt, legend handle dài 2.0.

In [3]:
plt.rcParams["font.family"] = "serif"
plt.rcParams["text.usetex"] = True
plt.rcParams["text.latex.preamble"] = r"\usepackage{amsmath}"
plt.rcParams["figure.dpi"] = 1000
plt.rcParams["font.size"] = 16
plt.rcParams["legend.fontsize"] = 16
plt.rcParams["xtick.direction"] = "in"
plt.rcParams["ytick.direction"] = "in"
plt.rcParams["xtick.major.size"] = 5.0
plt.rcParams["xtick.minor.size"] = 3.0
plt.rcParams["ytick.major.size"] = 5.0
plt.rcParams["ytick.minor.size"] = 3.0
plt.rcParams["axes.linewidth"] = 1.5
plt.rcParams["legend.handlelength"] = 2.0

In [ ]:
data  = pd.read_excel("../data/raw/training.xlsx", header=0) 
data.head()

,Year,Month,Day,Hour,Load,Site-1 Temp,Site-2 Temp,Site-3 Temp,Site-4 Temp,Site-5 Temp,Site-1 GHI,Site-2 GHI,Site-3 GHI,Site-4 GHI,Site-5 GHI
0,1,1,1,1,1997,8.0,8.2,5.3,9.4,8.1,0,0,0,0,0
1,1,1,1,2,1921,8.3,8.6,5.2,8.6,7.1,0,0,0,0,0
2,1,1,1,3,1861,8.1,8.8,5.1,8.7,6.2,0,0,0,0,0
3,1,1,1,4,1833,7.6,8.1,4.3,8.5,6.0,0,0,0,0,0
4,1,1,1,5,1847,7.3,7.5,4.0,8.6,6.9,0,0,0,0,0

In [14]:
response = data[data.columns[4]]
predictors = data[data.columns[5:]]

In [15]:
print(response)
print(predictors)

0        1997
1        1921
2        1861
3        1833
4        1847
         ...
17539    2545
17540    2449
17541    2348
17542    2229
17543    2118
Name: Load, Length: 17544, dtype: int64
       Site-1 Temp  Site-2 Temp  Site-3 Temp  Site-4 Temp  Site-5 Temp  \
0              8.0          8.2          5.3          9.4          8.1
1              8.3          8.6          5.2          8.6          7.1
2              8.1          8.8          5.1          8.7          6.2
3              7.6          8.1          4.3          8.5          6.0
4              7.3          7.5          4.0          8.6          6.9
...            ...          ...          ...          ...          ...
17539         12.5         11.9         10.3         12.6         11.3
17540         12.5         11.9          9.7         12.6         11.2
17541         12.5         12.0          9.7         12.7         11.1
17542         12.6         12.4          9.5         12.7         11.0
17543         12.4         12.1          9.7         12.5         10.6

       Site-1 GHI  Site-2 GHI  Site-3 GHI  Site-4 GHI  Site-5 GHI
0               0           0           0           0           0
1               0           0           0           0           0
2               0           0           0           0           0
3               0           0           0           0           0
4               0           0           0           0           0
...           ...         ...         ...         ...         ...
17539           0           0           0           0           0
17540           0           0           0           0           0
17541           0           0           0           0           0
17542           0           0           0           0           0
17543           0           0           0           0           0

[17544 rows x 10 columns]